
top-level:
  oc process -f template.yaml --param-file=param-file --ignore-unknown-parameters=true | oc create -f -
  oc describe
  oc get all -l app=appname
  oc whoami -t
  podman login -u $USER quay.io

build:
  env:
    oc set env bc simple --list
    oc set env bc simple key=value

  hook:
    oc set build-hook bc/name --post-commit --command --bundle exec  --verbose
    oc set build-hook bc/name --post-commit --script="curl http://api.com/user/${USER}"
    oc set build-hook bc/hook --post-commit -- bash -c "curl -s -S -i -X POST "http://routeurl/api/builds" -f -d 'developer=\${DEVELOPER}&git=\${OPENSHIFT_BUILD_SOURCE}&project=\${OPENSHIFT_BUILD_NAMESPACE}'"
    oc get bc simple -o jsonpath="{.spec.triggers[*].generic.secret}{"\n}"

  webhook:
    curl -X POST -k ${MA}/apis/build.openshift.io/v1/namespaces/${USER}-build-app/buildConfigs/simple/webhooks/{SECRET}/generic


deploy:

service:

route:
  oc get route -n openshift-image-registry
  IMAGE_STREAM=$(oc get route default-route -n openshift-image-registry -o jsonpath=${.spec.host})



template:
  oc get --export bc/name -o yaml
  oc get templates -n openshift
  oc get -o yaml -n openshift template <name>

  oc explain
  oc api-resources

images:
  oc import-image hello-world --confirm --from quay.io/redhattrainig/hello-world-nginx
  oc get istag
  oc describe is hello-world
  oc import-image php --from quay.io/$QU/php-70-rhel7 --confirm

skopeo:
  skopeo copy --dest-creds USER:TOKEN oci:/local_oci_image docker:/IMAGE_STREAM/Project/app:1.0
  skopeo copy oci:/local docker:/quay.io/kishorependyala/app:1.0
  skopeo inspect docker://quay.io/kishorependyala/php-info:1.0
  skopeo copy --docker-archive:abc.tar.gz docker://quay.io/user/app:latest

secret:
  oc create secret quayio --from-file .dockerconfigjson=/run/user/1000/containers/auth.json --type kubernetes.io/dockerconfigjson
  oc import-image php-info --confirm --reference-policy=local --from quay.io/kishorependyala/php-info:1.0
  oc policy add-role-to-group -n project1 system:image-puller system:serviceaccounts:project2
  oc secrets link builder secret-name

new-app:
  oc new-app --as-deployment-config --name test -i project/image
  oc new-app --as-deployment-config --name hello -i image

  oc new-app --as-deployment-config --name jhost --build-env MAVEN_MIRROR_URL=nexusurl \
  -i redhat-openjdk18-openshift:1.5 gitrooturl#branch --context-dir project-folder

  oc new-app --as-deployment-config --name trigger php~http://github.com/user/app --context-dir trigger-builds
  oc new-app --as-deployment-config --name hook php:7.3~http://github.com/user/app --context-dir post-commit

  s2i:
    oc new-app --as-deployment-config --name bonjour httpd:2.4~https://github.com/user/DO288-apps --context-dir s2i-scripts

trigger:
  oc describte bc/name
  oc set triggers bc/name --from-image=project/image:tag
  oc set triggers bc/name --from-image=project/image:tag --remove
  oc set triggers bc/name --from-gitlab
  oc set triggers bc/name --from-gitlab --remove
